services:
  ClientController:
    class: '../../modules/clients/client.controller'
    arguments:
      - '@ClientService'

  ClientService:
    class: '../../modules/clients/client.service'
    arguments:
      - '@LoggerService'

  LoggerService:
    class: '../../modules/logs/log.service'

  LogController:
    class: '../../modules/logs/log.controller'
    arguments:
      - '@LoggerService'
